name: qvim-baseline
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - torchvision=0.21.0
  - scikit-learn=1.6.1
  - matplotlib=3.10.1
  - lightning=2.5.1
  - pytorch=2.6.0
  - pandas=2.2.3
  - torchaudio=2.6.0
  - librosa>=0.10.0
  - notebook
  - wandb